export enum paths {
  home = "/",
  register = "/register",
  login = "/login",
  availableTimes = "/available-items",
  reservedTimes = "/reserved-items",
  adminPage = "/admin",
  users = "/users",
  resetPassword = "/resetPassword",
  editProfile = "/editProfile",
  viewProfile = "/profile",
  addPet = "/addPet",
  myPets = "/myPets",
  inventory = "/inventory",
  services = "/services",
  workers = "/workers",
  addWorker = "/addWorker",
}
