export enum paths {
  test = "/test",
  home = "/",
  availableTimes = "/available-items",
  reservedTimes = "/reserved-items",
  users = "/users",
  // Profile crud
  register = "/register",
  login = "/login",
  resetPassword = "/resetPassword",
  editProfile = "/editProfile",
  viewProfile = "/profile",
  // Services crud
  userServices = "/userServices",
  services = "/services",
  addService = "/addService",
  editService = "/editService",
  myServices = "/serviceHistory",
  // Pet crud
  addPet = "/addPet",
  myPets = "/myPets",
  // Worker crud
  workers = "/workers",
  addWorker = "/addWorker",
  editWorker = "/editWorker",
  // Inventory crud
  inventory = "/inventory",
  addInventory = "/addInventory",
  editInventory = "/editInventory",
}
